weights: yolov5s.pt
cfg: ''
data: ./data/rico2coco_clickable.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 300
batch_size: 128
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: true
sync_bn: false
workers: 8
project: rico2coco_clickable
entity: null
name: gpu12-test
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: 1
artifact_alias: latest
local_rank: 1
freeze: 10
patience: 10
save_dir: rico2coco_clickable/gpu12-test3
